//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novi_projekat_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOMITENTI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KOMITENTI()
        {
            this.DOKUMENTI = new HashSet<DOKUMENTI>();
        }
    
        public int ID_KOMITENTA { get; set; }
        public string NAZIV_KOMITENTA { get; set; }
        public string PIB { get; set; }
        public string PDV { get; set; }
        public string ADRESA { get; set; }
        public string GRAD { get; set; }
        public string KONTAKT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOKUMENTI> DOKUMENTI { get; set; }
    }
}
