//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novi_projekat_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAVKE
    {
        public Nullable<int> ID_DOKUMENTA { get; set; }
        public int ID_STAVKE { get; set; }
        public Nullable<int> RBR { get; set; }
        public Nullable<int> ID_ARTIKLA { get; set; }
        public string NAZIV_ARTIKLA { get; set; }
        public Nullable<decimal> KOLICINA { get; set; }
        public Nullable<decimal> CIJENA { get; set; }
        public Nullable<decimal> IZNOS { get; set; }
    
        public virtual ARTIKLI ARTIKLI { get; set; }
        public virtual DOKUMENTI DOKUMENTI { get; set; }
    }
}
